In [1]:
import pandas as pd

In [11]:
mammals = pd.read_csv(r'C:\Users\konga\Python_ds\Rdatasets\csv\MASS\mammals.csv', usecols=[0, 1, 2], index_col=0)

In [12]:
mammals

                               body    brain
Arctic fox                    3.385    44.50
Owl monkey                    0.480    15.50
Mountain beaver               1.350     8.10
Cow                         465.000   423.00
Grey wolf                    36.330   119.50
Goat                         27.660   115.00
Roe deer                     14.830    98.20
Guinea pig                    1.040     5.50
Verbet                        4.190    58.00
Chinchilla                    0.425     6.40
Ground squirrel               0.101     4.00
Arctic ground squirrel        0.920     5.70
African giant pouched rat     1.000     6.60
Lesser short-tailed shrew     0.005     0.14
Star-nosed mole               0.060     1.00
Nine-banded armadillo         3.500    10.80
Tree hyrax                    2.000    12.30
N.A. opossum                  1.700     6.30
Asian elephant             2547.000  4603.00
Big brown bat                 0.023     0.30
Donkey                      187.100   419.00
Horse                       521.000   655.00
European hedgehog             0.785     3.50
Patas monkey                 10.000   115.00
Cat                           3.300    25.60
Galago                        0.200     5.00
Genet                         1.410    17.50
Giraffe                     529.000   680.00
Gorilla                     207.000   406.00
Grey seal                    85.000   325.00
...                             ...      ...
African elephant           6654.000  5712.00
Water opossum                 3.500     3.90
Rhesus monkey                 6.800   179.00
Kangaroo                     35.000    56.00
Yellow-bellied marmot         4.050    17.00
Golden hamster                0.120     1.00
Mouse                         0.023     0.40
Little brown bat              0.010     0.25
Slow loris                    1.400    12.50
Okapi                       250.000   490.00
Rabbit                        2.500    12.10
Sheep                        55.500   175.00
Jaguar                      100.000   157.00
Chimpanzee                   52.160   440.00
Baboon                       10.550   179.50
Desert hedgehog               0.550     2.40
Giant armadillo              60.000    81.00
Rock hyrax-b                  3.600    21.00
Raccoon                       4.288    39.20
Rat                           0.280     1.90
E. American mole              0.075     1.20
Mole rat                      0.122     3.00
Musk shrew                    0.048     0.33
Pig                         192.000   180.00
Echidna                       3.000    25.00
Brazilian tapir             160.000   169.00
Tenrec                        0.900     2.60
Phalanger                     1.620    11.40
Tree shrew                    0.104     2.50
Red fox                       4.235    50.40

[62 rows x 2 columns]

In [13]:
mammals_body_weight = pd.Series(mammals.body)

In [14]:
mammals_body_weight

Arctic fox                      3.385
Owl monkey                      0.480
Mountain beaver                 1.350
Cow                           465.000
Grey wolf                      36.330
Goat                           27.660
Roe deer                       14.830
Guinea pig                      1.040
Verbet                          4.190
Chinchilla                      0.425
Ground squirrel                 0.101
Arctic ground squirrel          0.920
African giant pouched rat       1.000
Lesser short-tailed shrew       0.005
Star-nosed mole                 0.060
Nine-banded armadillo           3.500
Tree hyrax                      2.000
N.A. opossum                    1.700
Asian elephant               2547.000
Big brown bat                   0.023
Donkey                        187.100
Horse                         521.000
European hedgehog               0.785
Patas monkey                   10.000
Cat                             3.300
Galago                          0.200
Genet                           1.410
Giraffe                       529.000
Gorilla                       207.000
Grey seal                      85.000
                               ...
African elephant             6654.000
Water opossum                   3.500
Rhesus monkey                   6.800
Kangaroo                       35.000
Yellow-bellied marmot           4.050
Golden hamster                  0.120
Mouse                           0.023
Little brown bat                0.010
Slow loris                      1.400
Okapi                         250.000
Rabbit                          2.500
Sheep                          55.500
Jaguar                        100.000
Chimpanzee                     52.160
Baboon                         10.550
Desert hedgehog                 0.550
Giant armadillo                60.000
Rock hyrax-b                    3.600
Raccoon                         4.288
Rat                             0.280
E. American mole                0.075
Mole rat                        0.122
Musk shrew                      0.048
Pig                           192.000
Echidna                         3.000
Brazilian tapir               160.000
Tenrec                          0.900
Phalanger                       1.620
Tree shrew                      0.104
Red fox                         4.235
Name: body, Length: 62, dtype: float64

mammals_brain_weight = pd.Series(mammals.brain)

In [15]:
mammals_brain_weight = pd.Series(mammals.brain)

In [16]:
mammals_brain_weight

Arctic fox                     44.50
Owl monkey                     15.50
Mountain beaver                 8.10
Cow                           423.00
Grey wolf                     119.50
Goat                          115.00
Roe deer                       98.20
Guinea pig                      5.50
Verbet                         58.00
Chinchilla                      6.40
Ground squirrel                 4.00
Arctic ground squirrel          5.70
African giant pouched rat       6.60
Lesser short-tailed shrew       0.14
Star-nosed mole                 1.00
Nine-banded armadillo          10.80
Tree hyrax                     12.30
N.A. opossum                    6.30
Asian elephant               4603.00
Big brown bat                   0.30
Donkey                        419.00
Horse                         655.00
European hedgehog               3.50
Patas monkey                  115.00
Cat                            25.60
Galago                          5.00
Genet                          17.50
Giraffe                       680.00
Gorilla                       406.00
Grey seal                     325.00
                              ...
African elephant             5712.00
Water opossum                   3.90
Rhesus monkey                 179.00
Kangaroo                       56.00
Yellow-bellied marmot          17.00
Golden hamster                  1.00
Mouse                           0.40
Little brown bat                0.25
Slow loris                     12.50
Okapi                         490.00
Rabbit                         12.10
Sheep                         175.00
Jaguar                        157.00
Chimpanzee                    440.00
Baboon                        179.50
Desert hedgehog                 2.40
Giant armadillo                81.00
Rock hyrax-b                   21.00
Raccoon                        39.20
Rat                             1.90
E. American mole                1.20
Mole rat                        3.00
Musk shrew                      0.33
Pig                           180.00
Echidna                        25.00
Brazilian tapir               169.00
Tenrec                          2.60
Phalanger                      11.40
Tree shrew                      2.50
Red fox                        50.40
Name: brain, Length: 62, dtype: float64

In [29]:
brain_to_body = pd.Series(index=mammals.index, data=(mammals_brain_weight/1000/mammals_body_weight))

In [30]:
brain_to_body  #brain to body ratio

Arctic fox                   0.013146
Owl monkey                   0.032292
Mountain beaver              0.006000
Cow                          0.000910
Grey wolf                    0.003289
Goat                         0.004158
Roe deer                     0.006622
Guinea pig                   0.005288
Verbet                       0.013842
Chinchilla                   0.015059
Ground squirrel              0.039604
Arctic ground squirrel       0.006196
African giant pouched rat    0.006600
Lesser short-tailed shrew    0.028000
Star-nosed mole              0.016667
Nine-banded armadillo        0.003086
Tree hyrax                   0.006150
N.A. opossum                 0.003706
Asian elephant               0.001807
Big brown bat                0.013043
Donkey                       0.002239
Horse                        0.001257
European hedgehog            0.004459
Patas monkey                 0.011500
Cat                          0.007758
Galago                       0.025000
Genet                        0.012411
Giraffe                      0.001285
Gorilla                      0.001961
Grey seal                    0.003824
                               ...
African elephant             0.000858
Water opossum                0.001114
Rhesus monkey                0.026324
Kangaroo                     0.001600
Yellow-bellied marmot        0.004198
Golden hamster               0.008333
Mouse                        0.017391
Little brown bat             0.025000
Slow loris                   0.008929
Okapi                        0.001960
Rabbit                       0.004840
Sheep                        0.003153
Jaguar                       0.001570
Chimpanzee                   0.008436
Baboon                       0.017014
Desert hedgehog              0.004364
Giant armadillo              0.001350
Rock hyrax-b                 0.005833
Raccoon                      0.009142
Rat                          0.006786
E. American mole             0.016000
Mole rat                     0.024590
Musk shrew                   0.006875
Pig                          0.000937
Echidna                      0.008333
Brazilian tapir              0.001056
Tenrec                       0.002889
Phalanger                    0.007037
Tree shrew                   0.024038
Red fox                      0.011901
Length: 62, dtype: float64

In [39]:
percentage = brain_to_body*100 #percentage of brain weight in body weight
percentage

Arctic fox                   1.314623
Owl monkey                   3.229167
Mountain beaver              0.600000
Cow                          0.090968
Grey wolf                    0.328929
Goat                         0.415763
Roe deer                     0.662171
Guinea pig                   0.528846
Verbet                       1.384248
Chinchilla                   1.505882
Ground squirrel              3.960396
Arctic ground squirrel       0.619565
African giant pouched rat    0.660000
Lesser short-tailed shrew    2.800000
Star-nosed mole              1.666667
Nine-banded armadillo        0.308571
Tree hyrax                   0.615000
N.A. opossum                 0.370588
Asian elephant               0.180722
Big brown bat                1.304348
Donkey                       0.223944
Horse                        0.125720
European hedgehog            0.445860
Patas monkey                 1.150000
Cat                          0.775758
Galago                       2.500000
Genet                        1.241135
Giraffe                      0.128544
Gorilla                      0.196135
Grey seal                    0.382353
                               ...
African elephant             0.085843
Water opossum                0.111429
Rhesus monkey                2.632353
Kangaroo                     0.160000
Yellow-bellied marmot        0.419753
Golden hamster               0.833333
Mouse                        1.739130
Little brown bat             2.500000
Slow loris                   0.892857
Okapi                        0.196000
Rabbit                       0.484000
Sheep                        0.315315
Jaguar                       0.157000
Chimpanzee                   0.843558
Baboon                       1.701422
Desert hedgehog              0.436364
Giant armadillo              0.135000
Rock hyrax-b                 0.583333
Raccoon                      0.914179
Rat                          0.678571
E. American mole             1.600000
Mole rat                     2.459016
Musk shrew                   0.687500
Pig                          0.093750
Echidna                      0.833333
Brazilian tapir              0.105625
Tenrec                       0.288889
Phalanger                    0.703704
Tree shrew                   2.403846
Red fox                      1.190083
Length: 62, dtype: float64

In [40]:
print(percentage.loc['Human'])

2.129032258064516